### PR TITLE
read all the stat info, even when it exceeds 2048 bytes.

### PR DESCRIPTION
**Pull request by maplebed**
When the number of connected clients exceeds a small number, the client stats (example below) use up all 2048 bytes that are read off the socket. The result is that the actual metrics this script is looking for (latency etc.) are never read.

 /10.32.73.187:43992[1](queued=0,recved=635,sent=635)
 /10.158.12.47:60001[1](queued=0,recved=4208,sent=4208)
 /10.82.237.49:35073[1](queued=0,recved=19,sent=19)
^^^^ these lines repeat and blow out the buffer, preventing it from reading vvvv
Latency min/avg/max: 0/3/299
Received: 2206216
Sent: 2276700

### CODE REVIEW

**Comment by andreisavu** [comment]
Thanks! Please contribute this back to Apache ZooKeeper. This monitoring code is part of contrib:

https://github.com/apache/zookeeper/tree/trunk/src/contrib/monitoring
https://issues.apache.org/jira/browse/ZOOKEEPER

**Comment by maplebed** [comment]
Ok, I will, but since your repo is still the top hit in google when you search for 'ganglia zookeeper module', would you also accept the patch? Thanks.

**Comment by andreisavu** [comment]
Done. Thanks! I need to put a more visible notice that links to the contrib code.

**Comment by maplebed** [comment]
Thanks! Also, for future googling, https://issues.apache.org/jira/browse/ZOOKEEPER-1826 is the corresponding PR against the apache repo

**Pull request merged**
